FROM python:3.13.3-alpine3.20

RUN apk update && apk upgrade && apk add bash
WORKDIR /app

COPY frontend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY frontend/ .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]