version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: oss-monitor-backend
    volumes:
      - db_data:/app/db_data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///db_data/app.db
    restart: unless-stopped

volumes:
  db_data: